baseURL = 'http://example.org/'
languageCode = 'en-us'

theme = 'm10c'
publishDir = 'docs'
canonifyurls = true

paginate = 8


[params]
    description = 'Kazutoshi Akita'
    [[params.social]]
        icon = 'mail'
        name = 'Mail'
        url = 'mailto:sd21501@toyota-ti.ac.jp'
    [[params.socal]]
        icon = 'github'
        name = 'github'
        url = 'https://github.com/kakitamedia'
    [[params.socal]]
        icon = 'google_scholar'
        name = 'google_scholar'
        url = 'https://scholar.google.com/citations?user=9GC3j1wAAAAJ&hl=ja&oi=sra'


[params.style]
    darkestColor = "#e7e7e7"
    darkColor = "#ffffff"
    lightColor = "#000000"
    lightestColor = "#000000"
    primaryColor = "#000000"
    
