baseURL = 'https://kakitamedia.github.io/homepage'
languageCode = 'en-us'


theme = 'm10c'
publishDir = 'docs'
canonifyurls = true

paginate = 12


[params]
    description = 'Kazutoshi Akita'
    menu_item_separator = ' - '
    # avatar = 'images/temp.jpg'
    
    [[params.social]]
        icon = 'mail'
        url = 'mailto:sd21501@toyota-ti.ac.jp'

    [[params.social]]
        icon = "github"
        name = "My Github"
        url = "https://github.com/kakitamedia"
    


[params.style]
    darkestColor = "#e7e7e7"
    darkColor = "#ffffff"
    lightColor = "#000000"
    lightestColor = "#000000"
    primaryColor = "#0000ff"
    
